#!/usr/bin/env python3
"""Turn a kaypy game into a web page, in one command.

    kaypy web game.py          (or: python webbuild.py game.py, in a checkout)

That is the whole thing. It works out which images and sounds the script
uses by reading the script, copies them along with the engine, builds the
WASM bundle, then serves it and prints a URL to open. Ctrl-C stops the
server; the built site stays on disk (web_build/<name>/build/web/) and can
be uploaded as-is to itch.io or any static host.

Useful flags, none of them usually needed:

    --no-serve      build, but don't start the local server afterwards
    --no-build      only assemble the folder; print the pygbag command
    --port 9000     serve on a different port (default: 8000)
    --assets a b    copy these too, for files the script doesn't name
                    outright (a path built at runtime, say)
    --out DIR       write somewhere other than web_build/<script name>

WHY A GENERATED main.py: pygbag needs an explicit `asyncio.run(...)` at
the true top level of main.py — there's no way for it to auto-detect "the
script's setup finished, start the loop" the way native Python's atexit
lets kaypy do it. So this writes that one line into a separate, generated
main.py that imports your actual game file as a module (which runs its
whole top level — kaplay(), loadSprite(), add(), onKeyDown(), all of it,
exactly once, same as atexit firing after it natively) and then awaits the
engine's loop. Your lesson script itself stays byte-for-byte what the
Kaplay guide shows: no run() call anywhere in it.

The pygbag step downloads its CPython+SDL2-for-WASM runtime from
pygame-web.github.io the first time. Somewhere with a locked-down outbound
allowlist (a CI box, a sandboxed container) that fetch fails with a
network error that has nothing to do with this script or with kaypy — run
it from an ordinary machine with ordinary internet access instead.
"""
from __future__ import annotations
import argparse
import ast
import shutil
import socket
import subprocess
import sys
from pathlib import Path

# Where the engine itself lives. Under `pip install kaypy` this is inside
# site-packages, not a repo checkout, which is why it is resolved from this
# module rather than from a project directory.
KAPLAY_PKG = Path(__file__).resolve().parent

# Everything the build produces goes under the directory the user is
# standing in, for the same reason.
def default_out_dir(stem: str) -> Path:
    return Path.cwd() / "web_build" / stem

# What counts as an asset worth copying when it shows up as a string in
# the game script.
ASSET_SUFFIXES = {
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp",
    ".wav", ".ogg", ".mp3", ".flac",
    ".ttf", ".otf", ".json",
}

MAIN_PY_TEMPLATE = '''\
# /// script
# dependencies = [
#     "pygame.base",
# ]
# ///
"""Auto-generated by webbuild.py — do not hand-edit.
Regenerate it instead if the source game file changes.

The PEP 723 block above is load-bearing, not decoration: pygbag's own
in-browser bootstrap (pygbag/support/cpythonrc.py's preload_code(), which
runs against exactly this file's source) only links in the *real*,
compiled pygame WASM extension — the one with working pygame.init(),
pygame.display, etc. — when it finds a dependency block naming
"pygame.base". Without it, `import pygame` still succeeds (kaypy's own
nested `import pygame` inside kaplay/engine.py is never even visible to
pygbag's scanner, which only reads this top-level file, not what it
imports), but you silently get a stub missing every real function —
confirmed against a real build: it crashed with `AttributeError: module
'pygame' has no attribute 'init'` at the exact line kaypy calls
pygame.init(), and the in-browser boot log explicitly printed "# 696: no
pep 723 block found" right before it. Every kaypy web export needs this,
since the lesson script itself never writes `import pygame` — kaplay
does that internally, invisibly to pygbag's scanner — so this generated
wrapper is the only place that can declare it.
"""
import asyncio

import {module_name}  # noqa: F401  (import runs the whole game script)

from kaplay.engine import current_engine

asyncio.run(current_engine().run_async())
'''


# ---------------------------------------------------------------- assets

def find_assets(game_script: Path) -> list[str]:
    """Every asset the script names, as the script spells it.

    Reads the file rather than running it, and picks up any string
    literal that looks like an asset path — which covers loadSprite's
    single path, its list-of-frames form, loadSpriteAtlas's sheet and
    loadSound, without this needing to know about any of them. Paths are
    kept exactly as written ("images/bean.png", not an absolute path),
    because that spelling is what the script passes to loadSprite at
    runtime, and the copy has to land where the script will look for it.
    """
    try:
        tree = ast.parse(game_script.read_text(), filename=str(game_script))
    except SyntaxError as exc:
        raise SystemExit(f"{game_script} doesn't parse as Python: {exc}")

    base = game_script.parent
    found: list[str] = []
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Constant) and isinstance(node.value, str)):
            continue
        spelled = node.value
        if Path(spelled).suffix.lower() not in ASSET_SUFFIXES:
            continue
        if spelled in found:
            continue
        if not (base / spelled).is_file():
            continue
        if ".." in Path(spelled).parts or Path(spelled).is_absolute():
            print(f"note: skipping {spelled} — only paths inside the script's own "
                  f"folder can be copied; pass it with --assets if you need it")
            continue
        found.append(spelled)
    return found


# ------------------------------------------------------------ audio prep

def _convert_via_ffmpeg(ffmpeg: str, wav_path: Path, ogg_path: Path) -> bool:
    result = subprocess.run(
        [ffmpeg, "-y", "-loglevel", "error", "-i", str(wav_path), str(ogg_path)],
        capture_output=True,
    )
    return result.returncode == 0 and ogg_path.is_file()


def _convert_via_imageio_ffmpeg(wav_path: Path, ogg_path: Path) -> bool:
    # Pure-`pip install` fallback for machines without ffmpeg on PATH (no
    # Homebrew, no system package manager) — imageio-ffmpeg's wheel bundles
    # an actual static ffmpeg binary per-platform, so `pip install
    # imageio-ffmpeg` alone is enough. (A `soundfile`-only pure-Python
    # fallback was tried first, but its bundled libsndfile OGG/Vorbis
    # encoder segfaulted, silently, on a real 22.05kHz mono .wav in testing
    # — a real ffmpeg binary doesn't have that problem, so that's what
    # this uses instead.)
    try:
        import imageio_ffmpeg
    except ImportError:
        return False
    try:
        exe = imageio_ffmpeg.get_ffmpeg_exe()
    except Exception:
        return False
    return _convert_via_ffmpeg(exe, wav_path, ogg_path)


def convert_wav_to_ogg(out_dir: Path) -> tuple[list[str], list[str]]:
    """pygbag's own --build step hard-fails on .wav/.mp3/.aiff assets
    ("has a common unsupported format. Use OGG format instead.") because
    browsers' WASM SDL2-mixer can't reliably decode most of those
    encodings. Rather than just suppressing that error (which would still
    ship a file that may not actually play in the browser), convert each
    .wav to a same-named .ogg here — via ffmpeg if it's on PATH, otherwise
    via the `imageio-ffmpeg` package. Every conversion runs in a separate
    process, so a crash in an encoder can never take this tool down with
    it. AssetManager.loadSound (kaplay/assets.py) then prefers that
    sibling .ogg automatically whenever sys.platform == "emscripten", so
    the game script itself never needs to know or care."""
    ffmpeg = shutil.which("ffmpeg")
    converted, unconverted = [], []
    for wav_path in sorted(out_dir.rglob("*.wav")):
        rel = str(wav_path.relative_to(out_dir))
        ogg_path = wav_path.with_suffix(".ogg")
        if ogg_path.exists():
            converted.append(rel)  # already had one alongside the source .wav
            continue
        ok = ffmpeg is not None and _convert_via_ffmpeg(ffmpeg, wav_path, ogg_path)
        if not ok:
            ok = _convert_via_imageio_ffmpeg(wav_path, ogg_path)
        (converted if ok else unconverted).append(rel)
    return converted, unconverted


# ---------------------------------------------------------------- build

def assemble(game_script: Path, extra_assets: list[Path], out_dir: Path) -> tuple[Path, list[str]]:
    if not game_script.is_file():
        raise SystemExit(f"no such game script: {game_script}")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    # 1. the engine itself — minus the starter assets, which are only there
    #    for `kaypy new` and would otherwise bloat every web build by
    #    several megabytes of sprites the game may not even use.
    shutil.copytree(
        KAPLAY_PKG, out_dir / "kaplay",
        ignore=shutil.ignore_patterns("starter", "__pycache__", "*.pyc"),
    )

    # 2. the game script, kept under its own name so `import <name>` in
    #    the generated main.py runs it (main.py is reserved for the
    #    wrapper pygbag actually launches).
    module_name = game_script.stem
    shutil.copy2(game_script, out_dir / f"{module_name}.py")

    # 3. the assets the script asks for, each landing at exactly the path
    #    the script spells, so its own loadSprite()/loadSound() calls find
    #    them unchanged.
    used = find_assets(game_script)
    for spelled in used:
        src = game_script.parent / spelled
        dest = out_dir / spelled
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)

    # 4. anything named with --assets, for paths the script builds at
    #    runtime rather than spelling out.
    for src in extra_assets:
        if not src.exists():
            print(f"warning: --assets path {src} does not exist, skipping")
            continue
        dest = out_dir / src.name
        if src.is_dir():
            shutil.copytree(src, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(src, dest)

    # 5. the generated pygbag entry point
    (out_dir / "main.py").write_text(MAIN_PY_TEMPLATE.format(module_name=module_name))

    return out_dir, used


# ---------------------------------------------------------------- serve

def pick_port(preferred: int) -> int:
    for port in range(preferred, preferred + 10):
        with socket.socket() as s:
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                continue
    raise SystemExit(f"ports {preferred}-{preferred + 9} are all busy — pass --port")


def serve(web_dir: Path, preferred_port: int):
    if not web_dir.is_dir():
        print(f"\nnothing to serve: {web_dir} doesn't exist (did the build fail above?)")
        return
    port = pick_port(preferred_port)
    print("\n" + "=" * 62)
    print(f"  Your game is running at:  http://localhost:{port}")
    print("=" * 62)
    print("\nOpen that in a browser and click the page once to start it.")
    print("Press Ctrl-C here when you're done.\n")
    try:
        subprocess.run(
            [sys.executable, "-m", "http.server", str(port), "--directory", str(web_dir)],
            check=False,
        )
    except KeyboardInterrupt:
        pass
    print(f"\nServer stopped. The built site is still at:\n    {web_dir}")
    print("Upload that folder as-is to itch.io or any static host to publish it.")


# ----------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("game_script", type=Path, help="the kaypy game .py file to put on the web")
    ap.add_argument("--out", type=Path, default=None,
                    help="output folder [default: web_build/<game script name>]")
    ap.add_argument("--assets", nargs="*", type=Path, default=[],
                    help="extra files/folders to copy, for assets the script doesn't spell out")
    ap.add_argument("--no-build", action="store_true",
                    help="only assemble the folder; don't run pygbag")
    ap.add_argument("--no-serve", action="store_true",
                    help="build, but don't start a local server afterwards")
    ap.add_argument("--port", type=int, default=8000, help="port for the local server [default: 8000]")
    args = ap.parse_args()

    game_script = args.game_script.resolve()
    out_dir = (args.out or default_out_dir(args.game_script.stem)).resolve()
    out_dir, used = assemble(game_script, [p.resolve() for p in args.assets], out_dir)

    print(f"Assembled {game_script.name} for the web in {out_dir}")
    if used:
        print(f"  assets found in the script ({len(used)}): {', '.join(used)}")
    else:
        print("  no asset files named in the script — if it does load some, pass --assets")

    converted, unconverted = convert_wav_to_ogg(out_dir)
    if converted:
        via = "ffmpeg" if shutil.which("ffmpeg") else "imageio-ffmpeg"
        print(f"  converted for the browser ({via}): {', '.join(converted)}")
    disable_sound_format_error = bool(unconverted)
    if unconverted:
        print(f"\nWarning: couldn't produce a .ogg for: {', '.join(unconverted)}.")
        print("Passing --disable-sound-format-error so the build doesn't hard-fail on")
        print("them, but the original file may not actually play in every browser.")
        print("Fix it with (no Homebrew/system package manager needed):")
        print("    pip install imageio-ffmpeg")
        print("...then run this again.")

    pygbag_cmd = [sys.executable, "-m", "pygbag", "--build"]
    # pygbag's default (--can_close 0) registers a beforeunload handler
    # that calls confirm("Are you sure you want to navigate away...?").
    # Modern Chrome and Safari block synchronous confirm() during
    # beforeunload outright, and rather than failing quietly that knocks
    # pygbag's runtime into a fetch -> click -> blocked-confirm -> reboot
    # loop that never gets as far as running the game. --can_close 1
    # skips the handler entirely.
    pygbag_cmd += ["--can_close", "1"]
    if disable_sound_format_error:
        pygbag_cmd.append("--disable-sound-format-error")
    pygbag_cmd.append(str(out_dir))

    if args.no_build:
        print("\n--no-build given, so stopping here. To finish it yourself:\n")
        print("    " + " ".join(pygbag_cmd) + "\n")
        return

    print(f"\nBuilding the web version (this needs internet the first time)...\n")
    result = subprocess.run(pygbag_cmd, check=False)
    if result.returncode != 0:
        raise SystemExit(
            "\npygbag failed (see its output above). If it couldn't reach\n"
            "pygame-web.github.io, that's the WASM runtime download — it needs\n"
            "ordinary internet access, and a sandboxed or allowlisted network\n"
            "will block it."
        )

    web_dir = out_dir / "build" / "web"
    if args.no_serve:
        print(f"\nBuilt: {web_dir}")
        print("Serve that folder with any static server (not file://) to try it,")
        print("or upload it as-is to itch.io / any static host.")
        return

    serve(web_dir, args.port)


if __name__ == "__main__":
    main()
